export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  TURNAROUND_NOT_FOUND: "TURNAROUND_NOT_FOUND",
  BOOKING_NOT_FOUND: "BOOKING_NOT_FOUND",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  RELEASE_CHECK_FAILED: "RELEASE_CHECK_FAILED",
  RESOURCE_UNAVAILABLE: "RESOURCE_UNAVAILABLE",
  REBIND_CONFLICT: "REBIND_CONFLICT"
} as const;
